create table IF NOT EXISTS `STU_INFO` (
  `STU_ID`          INT            AUTO_INCREMENT
  COMMENT '应聘者ID',
  `STU_IN_JOB`      VARCHAR(10) COMMENT '是否在职',
  `STU_IN_JOB_COMP` VARCHAR(200) COMMENT '在职单位',
  `USER_ID`         INTEGER   NOT NULL
  COMMENT '用户ID',
  `IS_DELETE`       INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`  TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`STU_ID`)
)
  COMMENT = '应聘者基本信息表';
create table IF NOT EXISTS `STU_EDU_INFO` (
  `EDU_ID`              INT               AUTO_INCREMENT
  COMMENT '教育ID',
  `EDU_DEGREE`          INTEGER      NOT NULL
  COMMENT '学位',
  `EDU_SCHOOL`          VARCHAR(200) NOT NULL
  COMMENT '学校名称',
  `EDU_SCHOOL_COUNTRY`  VARCHAR(10)  NOT NULL
  COMMENT '学校国别',
  `EDU_SCHOOL_LOCATION` INTEGER      NOT NULL
  COMMENT '学校所在地',
  `EDU_MAJOR`           INTEGER      NOT NULL
  COMMENT '专业',
  `EDU_COLLEGE`         VARCHAR(200) COMMENT '学院（选填）',
  `EDU_GPA`             DECIMAL COMMENT 'GPA（选填）',
  `EDU_START`           DATE         NOT NULL
  COMMENT '入学时间',
  `EDU_END`             DATE         NOT NULL
  COMMENT '毕业时间',
  `STU_ID`              INTEGER      NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`           INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`      TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`EDU_ID`)
)
  COMMENT = '应聘者教育信息表';
create table IF NOT EXISTS `STU_SUB_INFO` (
  `SUB_ID`          INT            AUTO_INCREMENT
  COMMENT '附加信息ID',
  `SUB_COURSE`      VARCHAR(200) COMMENT '相关课程信息',
  `SUB_HONOR`       VARCHAR(200) COMMENT '相关荣誉',
  `SUB_AWARD`       VARCHAR(200) COMMENT '相关奖项',
  `SUB_SKILL`       VARCHAR(200) COMMENT '相关技能',
  `SUB_CERTIFICATE` VARCHAR(200) COMMENT '相关证书',
  `SUB_CERTIF_URL`  VARCHAR(200) COMMENT '证书上传',
  `SUB_FOREIGN`     VARCHAR(200) COMMENT '外语语言',
  `SUB_INTEREST`    VARCHAR(200) COMMENT '兴趣特长',
  `SUB_ACTIVITY`    VARCHAR(200) COMMENT '组织活动',
  `STU_ID`          INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`       INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`  TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`SUB_ID`)
)
  COMMENT = '应聘者附加新息表';
create table IF NOT EXISTS `STU_PROJECT` (
  `PROJ_ID`           INT               AUTO_INCREMENT
  COMMENT '项目ID',
  `PROJ_NAME`         VARCHAR(200) NOT NULL
  COMMENT '研究项目名称',
  `PROJ_ROLE`         VARCHAR(200) NOT NULL
  COMMENT '担任角色',
  `PROJ_START_TIME`   DATE         NOT NULL
  COMMENT '开始时间',
  `PROJ_END_TIME`     DATE         NOT NULL
  COMMENT '结束时间',
  `PROJ_DELIVER`      VARCHAR(200) COMMENT '研究成果',
  `DELEVER_PUBLISH`   INTEGER      NOT NULL
  COMMENT '成果是否发表',
  `DELEVER_PUB_INSTI` VARCHAR(200) COMMENT '发表机构',
  `STU_ID`            INTEGER      NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`         INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`    TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`PROJ_ID`)
)
  COMMENT = '相关研究表';
create table IF NOT EXISTS `STU_WORK` (
  `WORK_ID`         INT               AUTO_INCREMENT
  COMMENT '工作ID',
  `WORK_COMPANY`    VARCHAR(200) NOT NULL
  COMMENT '实习公司名称',
  `WORK_LOCATION`   INTEGER COMMENT '实习公司城市',
  `WORK_POSITION`   VARCHAR(200) NOT NULL
  COMMENT '实习职位',
  `WORK_SECTOR`     VARCHAR(200) COMMENT '所在部门（选填）',
  `WORK_START_TIME` DATE         NOT NULL
  COMMENT '开始时间',
  `WORK_END_TIME`   DATE         NOT NULL
  COMMENT '结束时间',
  `WORK_DUTY`       VARCHAR(200) NOT NULL
  COMMENT '工作内容',
  `WORK_NATURE`     INTEGER      NOT NULL
  COMMENT '工作性质',
  `STU_ID`          INTEGER      NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`       INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`  TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`WORK_ID`)
)
  COMMENT = '工作经验表';
create table IF NOT EXISTS `STU_ACTIVITY` (
  `ACT_ID`           INT               AUTO_INCREMENT
  COMMENT '活动ID',
  `ACT_NAME`         VARCHAR(200) NOT NULL
  COMMENT '活动名称',
  `ACT_ORGANIZATION` VARCHAR(200) COMMENT '组织活动单位',
  `ACT_ROLE`         VARCHAR(200) NOT NULL
  COMMENT '担任角色',
  `ACT_START_TIME`   DATE         NOT NULL
  COMMENT '开始时间',
  `ACT_END_TIME`     DATE         NOT NULL
  COMMENT '结束时间',
  `ACT_DETAIL`       VARCHAR(200) NOT NULL
  COMMENT '活动内容',
  `STU_ID`           INTEGER      NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`        INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`   TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`ACT_ID`)
)
  COMMENT = '组织活动表';
create table IF NOT EXISTS `STU_ADVAN_LABEL` (
  `LABEL_ID`       INT UNSIGNED   AUTO_INCREMENT
  COMMENT '标签ID',
  `LABEL_NUM`      INTEGER   NOT NULL
  COMMENT '优势标签',
  `STU_ID`         INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`LABEL_ID`)
)
  COMMENT = '应聘者优势标签表';
create table IF NOT EXISTS `STU_PREFER_PROF` (
  `PRE_PROF_ID`    INT UNSIGNED   AUTO_INCREMENT
  COMMENT '意向ID',
  `PRE_PROF_NUM`   INTEGER   NOT NULL
  COMMENT '意向职业',
  `PRE_AVAIL_TIME` DATE      NOT NULL
  COMMENT '预计到岗时间',
  `STU_ID`         INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`PRE_PROF_ID`)
)
  COMMENT = '应聘者意向职业表';
create table IF NOT EXISTS `STU_PREFER_INDUSTRY` (
  `PRE_IND_ID`     INT UNSIGNED   AUTO_INCREMENT
  COMMENT '意向ID',
  `PRE_IND_NUM`    INTEGER   NOT NULL
  COMMENT '意向行业',
  `STU_ID`         INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`PRE_IND_ID`)
)
  COMMENT = '应聘者意向行业表';
create table IF NOT EXISTS `STU_PREFER_CITY` (
  `PRE_CITY_ID`    INT UNSIGNED   AUTO_INCREMENT
  COMMENT '意向ID',
  `PRE_REGION_NUM` INTEGER   NOT NULL
  COMMENT '意向城市',
  `STU_ID`         INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`PRE_CITY_ID`)
)
  COMMENT = '应聘者意向城市表';
create table IF NOT EXISTS `STU_PREFER_SALARY` (
  `PRE_SALA_ID`    INT UNSIGNED   AUTO_INCREMENT
  COMMENT '薪资ID',
  `PRE_SALA_CAP`   INTEGER COMMENT '意向薪资下限',
  `PRE_SALA_FLOOR` INTEGER COMMENT '意向薪资上限',
  `STU_ID`         INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`PRE_SALA_ID`)
)
  COMMENT = '应聘者意向薪资';
create table IF NOT EXISTS `STU_INTRODUCTION_VIDEO` (
  `INTRO_VIDEO_ID`   INT UNSIGNED   AUTO_INCREMENT
  COMMENT '视频ID',
  `INTRO_VIDEO_PATH` INTEGER   NOT NULL
  COMMENT '视频存储路径',
  `STU_ID`           INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`        INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`   TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`INTRO_VIDEO_ID`)
)
  COMMENT = '应聘者介绍视频表';
create table IF NOT EXISTS `STU_RESUME_TEMPLATE` (
  `TEMPLATE_ID`    INT               AUTO_INCREMENT
  COMMENT '模板ID',
  `TEMPLATE_PATH`  VARCHAR(400) NOT NULL
  COMMENT '模板存储路径',
  `STU_ID`         INTEGER      NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`      INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`TEMPLATE_ID`)
)
  COMMENT = '应聘者简历模板表';
create table IF NOT EXISTS `STU_NOTIFICATION` (
  `NOTIFY_ID`      INT UNSIGNED AUTO_INCREMENT
  COMMENT '通知ID',
  `NOTIFY_CONTENT` VARCHAR(800) NOT NULL
  COMMENT '通知信息',
  `NOTIFY_TIME`    TIMESTAMP    NOT NULL
  COMMENT '通知时间',
  `NOTIFY_READ`    INTEGER      NOT NULL
  COMMENT '是否阅读',
  `STU_ID`         INTEGER      NOT NULL
  COMMENT '应聘者ID',
  PRIMARY KEY (`NOTIFY_ID`)
)
  COMMENT = '系统通知表';
create table IF NOT EXISTS `HR_INFO` (
  `HR_ID`          INT            AUTO_INCREMENT
  COMMENT '招聘者ID',
  `COMPANY_ID`     INTEGER   NOT NULL
  COMMENT '所属企业',
  `HR_ON_JOB`      INTEGER   NOT NULL
  COMMENT '在职验证',
  `USER_ID`        INTEGER   NOT NULL
  COMMENT '用户ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`HR_ID`)
)
  COMMENT = '招聘者基本信息表';
create table IF NOT EXISTS `COMPANY_INFO` (
  `COMPANY_ID`         INT               AUTO_INCREMENT
  COMMENT '企业ID',
  `COMPANY_NAME`       VARCHAR(200) NOT NULL
  COMMENT '企业名称',
  `COMPANY_CODE`       VARCHAR(200) NOT NULL
  COMMENT '企业三证号码',
  `COMPANY_COUNTRY`    VARCHAR(10)  NOT NULL
  COMMENT '企业国别',
  `COMPANY_INTRODUC`   VARCHAR(200) COMMENT '企业简介',
  `COMPANY_SCALE_NUM`  INTEGER      NOT NULL
  COMMENT '企业规模',
  `COMPANY_NATURE`     VARCHAR(200) NOT NULL
  COMMENT '企业性质',
  `COMPANY_LOCATION`   VARCHAR(200) NOT NULL
  COMMENT '企业所在地',
  `COMPANY_MAIL`       VARCHAR(200) COMMENT '企业邮箱',
  `COMPANY_WEBSITE`    VARCHAR(200) COMMENT '企业官网',
  `COMPANY_START_DATE` DATE COMMENT '成立日期',
  `COMPANY_LOGO`       VARCHAR(200) COMMENT '企业LOGO',
  `COMPANY_VERIFY`     INTEGER      NOT NULL
  COMMENT '企业认证',
  `USER_ID`            INTEGER      NOT NULL
  COMMENT '录入人ID',
  `IS_DELETE`          INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`     TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`COMPANY_ID`)
)
  COMMENT = '企业基本信息表';
create table IF NOT EXISTS `COMPANY_INDUSTRY` (
  `COMPANY_INDUS_ID` INT            AUTO_INCREMENT
  COMMENT '企业所属行业ID',
  `IND_NUM`          INTEGER   NOT NULL
  COMMENT '行业ID',
  `COMPANY_ID`       INTEGER   NOT NULL
  COMMENT '企业ID',
  `IS_DELETE`        INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`   TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`COMPANY_INDUS_ID`)
)
  COMMENT = '企业所属行业表';
create table IF NOT EXISTS `COMPANY_VERIFICAITON` (
  `VERIFY_ID`       INT            AUTO_INCREMENT
  COMMENT '认证ID',
  `VERIFY_TIME`     DATE      NOT NULL
  COMMENT '认证时间',
  `VERIFY_END_TIME` DATE      NOT NULL
  COMMENT '到期时间',
  `OPER_USER_ID`    INTEGER   NOT NULL
  COMMENT '操作人',
  `COMPANY_ID`      INTEGER   NOT NULL
  COMMENT '企业ID',
  `IS_DELETE`       INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`  TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`VERIFY_ID`)
)
  COMMENT = '企业认证表';
create table IF NOT EXISTS `JOB_INFO` (
  `JOB_ID`          INT               AUTO_INCREMENT
  COMMENT '职位ID',
  `JOB_NAME`        VARCHAR(200) NOT NULL
  COMMENT '职位名称',
  `JOB_PROF_NUM`    INTEGER      NOT NULL
  COMMENT '职位类别编号',
  `JOB_START_TIME`  DATE         NOT NULL
  COMMENT '职位起始时间',
  `JOB_END_TIME`    DATE         NOT NULL
  COMMENT '职位截止时间',
  `JOB_TIME`        INTEGER      NOT NULL
  COMMENT '职位性质',
  `JOB_DESCRIPTION` VARCHAR(200) NOT NULL
  COMMENT '职位描述',
  `JOB_DUTY`        VARCHAR(200) COMMENT '职责描述',
  `JOB_REQ`         VARCHAR(200) COMMENT '学历要求',
  `JOB_LOCATION`    VARCHAR(200) NOT NULL
  COMMENT '工作地点',
  `JOB_HIGHLIGHT`   VARCHAR(200) COMMENT '职位亮点',
  `JOB_SALARY`      VARCHAR(200) COMMENT '职位薪资（非必填）',
  `CV_RECEI_MAIL`   VARCHAR(200) NOT NULL
  COMMENT '简历接收邮箱',
  `CV_NAME_RULE`    VARCHAR(200) COMMENT '简历命名规则',
  `JOB_ACTIVE`      INTEGER      NOT NULL
  COMMENT '职位状态',
  `HR_ID`           INTEGER      NOT NULL
  COMMENT '招聘者ID',
  `COMPANY_ID`      INTEGER      NOT NULL
  COMMENT '企业ID',
  `IS_DELETE`       INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`  TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`JOB_ID`)
)
  COMMENT = '职位基本信息表';
create table IF NOT EXISTS `JOB_INDUSTRY` (
  `JOB_IND_ID`     INT            AUTO_INCREMENT
  COMMENT '行业ID',
  `JOB_IND_NUM`    INTEGER   NOT NULL
  COMMENT '行业编号',
  `JOB_ID`         INTEGER   NOT NULL
  COMMENT '职位ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`JOB_IND_ID`)
)
  COMMENT = '职位行业表';
create table IF NOT EXISTS `HR_VIDEO_INVITATION` (
  `INVITE_ID`     INT AUTO_INCREMENT
  COMMENT '邀请ID',
  `INVITE_TIME`   TIMESTAMP NOT NULL
  COMMENT '邀请时间',
  `INVITE_STU_ID` INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `INVITE_HR_ID`  INTEGER   NOT NULL
  COMMENT '邀请人ID',
  PRIMARY KEY (`INVITE_ID`)
)
  COMMENT = '视频邀请表';
create table IF NOT EXISTS `STU_JOB_COLLECT` (
  `COLEECT_ID`     INT            AUTO_INCREMENT
  COMMENT '收藏ID',
  `JOB_ID`         INTEGER   NOT NULL
  COMMENT '职位ID',
  `JOB_COLL_TIME`  DATE      NOT NULL
  COMMENT '职位收藏时间',
  `STU_ID`         INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`      INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`COLEECT_ID`)
)
  COMMENT = '职位信息收藏表';
create table IF NOT EXISTS `STU_COMP_COLLECT` (
  `COLEECT_ID`        INT UNSIGNED   AUTO_INCREMENT
  COMMENT '收藏ID',
  `COMPANY_ID`        INTEGER   NOT NULL
  COMMENT '企业ID',
  `COMPANY_COLL_TIME` DATE      NOT NULL
  COMMENT '企业收藏时间',
  `STU_ID`            INTEGER   NOT NULL
  COMMENT '应聘者ID',
  `IS_DELETE`         INTEGER   NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`    TIMESTAMP NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`COLEECT_ID`)
)
  COMMENT = '企业信息收藏表';
create table IF NOT EXISTS `STU_JOB_APPLY` (
  `APPLY_ID`         INT UNSIGNED AUTO_INCREMENT
  COMMENT '申请ID',
  `STU_ID`           INTEGER      NOT NULL
  COMMENT '应聘者ID',
  `JOB_ID`           INTEGER      NOT NULL
  COMMENT '职位ID',
  `JOB_CV_SEND`      TIMESTAMP    NOT NULL
  COMMENT '简历是否发送',
  `JOB_APPLY_TIME`   INTEGER      NOT NULL
  COMMENT '职位申请时间',
  `JOB_APPLY_STATUS` VARCHAR(200) NOT NULL
  COMMENT '职位申请状态',
  PRIMARY KEY (`APPLY_ID`)
)
  COMMENT = '职位申请记录表';
create table IF NOT EXISTS `SYS_MAJOR` (
  `MAJOR_NUM`      INT               AUTO_INCREMENT
  COMMENT '专业编号',
  `MAJOR_ABBRE`    VARCHAR(100) COMMENT '专业简称',
  `MAJOR_CHN`      VARCHAR(100) NOT NULL
  COMMENT '专业中文全称',
  `MAJOR_ENG`      VARCHAR(100) NOT NULL
  COMMENT '专业英文全称',
  `MAJOR_LEVEL`    VARCHAR(100) NOT NULL
  COMMENT '专业分级',
  `START_DATE`     TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  `IS_DELETE`      INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`MAJOR_NUM`)
)
  COMMENT = '专业分类表';
create table IF NOT EXISTS `SYS_DEGREE` (
  `DEGREE_NUM` INT AUTO_INCREMENT
  COMMENT '学位编号',
  `DEGREE_CHN` VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `DEGREE_ENG` VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `START_DATE` TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  PRIMARY KEY (`DEGREE_NUM`)
)
  COMMENT = '学位表';
create table IF NOT EXISTS `SYS_LABEL_CLASS` (
  `LABEL_NUM`      INT               AUTO_INCREMENT
  COMMENT '标签编号',
  `LABEL_CHN`      VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `LABEL_ENG`      VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `START_DATE`     VARCHAR(100) NOT NULL
  COMMENT '启用时间',
  `IS_DELETE`      VARCHAR(100) NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`LABEL_NUM`)
)
  COMMENT = '优势标签表';
create table IF NOT EXISTS `SYS_PROF_CLASS` (
  `PROF_NUM`       INT               AUTO_INCREMENT
  COMMENT '职业编号',
  `PROF_CHN`       VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `PROF_ENG`       VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `START_DATE`     TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  `IS_DELETE`      INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`PROF_NUM`)
)
  COMMENT = '职业信息分类表';
create table IF NOT EXISTS `SYS_IND_CLASS` (
  `IND_NUM`        INT               AUTO_INCREMENT
  COMMENT '行业编号',
  `IND_CHN`        VARCHAR(100) NOT NULL
  COMMENT '行业中文名称',
  `IND_ENG`        VARCHAR(100) NOT NULL
  COMMENT '行业英文名称',
  `IND_LEVEL`      INTEGER      NOT NULL
  COMMENT '行业分类级别',
  `IND_PARENT_NUM` INTEGER      NOT NULL
  COMMENT '上级行业代码',
  `START_DATE`     TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  `IS_DELETE`      INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`IND_NUM`)
)
  COMMENT = '行业信息分类表';
create table IF NOT EXISTS `SYS_COMPANY_SCALE` (
  `SCALE_NUM`  INT AUTO_INCREMENT
  COMMENT '规模编号',
  `SCALE_CHN`  VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `SCALE_ENG`  VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `START_DATE` TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  PRIMARY KEY (`SCALE_NUM`)
)
  COMMENT = '企业规模表';
create table IF NOT EXISTS `SYS_COMPANY_NATURE` (
  `NATURE_NUM` INT AUTO_INCREMENT
  COMMENT '性质编号',
  `NATURE_CHN` VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `NATURE_ENG` VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `START_DATE` TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  PRIMARY KEY (`NATURE_NUM`)
)
  COMMENT = '企业性质表';
create table IF NOT EXISTS `SYS_COUNTRY` (
  `COUNTRY_ABBRE`  INT               AUTO_INCREMENT
  COMMENT '国别简写',
  `COUNTRY_CHN`    VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `COUNTRY_ENG`    VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `START_DATE`     TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  `IS_DELETE`      INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME` TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`COUNTRY_ABBRE`)
)
  COMMENT = '国别表';
create table IF NOT EXISTS `SYS_CHN_REGION` (
  `REGION_NUM`        INT               AUTO_INCREMENT
  COMMENT '区划编号',
  `REGION_CHN`        VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `REGION_ENG`        VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `REGION_LEVEL`      INTEGER      NOT NULL
  COMMENT '行政区划级别',
  `REGION_PARENT_NUM` INTEGER      NOT NULL
  COMMENT '上级区划代码',
  `START_DATE`        TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  `IS_DELETE`         INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`    TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`REGION_NUM`)
)
  COMMENT = '中国行政区划表';
create table IF NOT EXISTS `SYS_USA_REGION` (
  `REGION_NUM`        INT               AUTO_INCREMENT
  COMMENT '区划编号',
  `REGION_CHN`        VARCHAR(100) NOT NULL
  COMMENT '中文描述',
  `REGION_ENG`        VARCHAR(100) NOT NULL
  COMMENT '英文描述',
  `REGION_LEVEL`      INTEGER      NOT NULL
  COMMENT '行政区划级别',
  `REGION_PARENT_NUM` INTEGER      NOT NULL
  COMMENT '上级区划代码',
  `START_DATE`        TIMESTAMP    NOT NULL
  COMMENT '启用时间',
  `IS_DELETE`         INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`    TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`REGION_NUM`)
)
  COMMENT = '美国地区表';
create table IF NOT EXISTS `SYS_USER_ROLE` (
  `ROLE_ID`          INT AUTO_INCREMENT
  COMMENT '角色ID',
  `ROLE_TYPE`        INTEGER      NOT NULL
  COMMENT '角色类型',
  `ROLE_DESCRPTIPON` VARCHAR(100) NOT NULL
  COMMENT '角色描述',
  `IS_DELETE`        INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`   TIMESTAMP    NOT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`ROLE_ID`)
)
  COMMENT = '用户角色表';
create table IF NOT EXISTS `SYS_ROLE_PERMISSION` (
  `PERMI_ID`          INT AUTO_INCREMENT
  COMMENT '权限ID',
  `PERMI_TYPE`        INTEGER      NOT NULL
  COMMENT '权限类型',
  `PERMI_DESCRPTIPON` VARCHAR(100) NOT NULL
  COMMENT '权限描述',
  `PERMI_FUNCTION`    VARCHAR(100) NOT NULL
  COMMENT '权限功能',
  `IS_DELETE`         INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`    TIMESTAMP    NOT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`PERMI_ID`)
)
  COMMENT = '用户权限表';
create table IF NOT EXISTS `SYS_USER` (
  `USER_ID`          INT               AUTO_INCREMENT
  COMMENT '用户ID',
  `USER_NAME`        VARCHAR(200) NOT NULL
  COMMENT '登录名',
  `USER_PASS`        VARCHAR(200) NOT NULL
  COMMENT '密码',
  `USER_REGIST_DATE` TIMESTAMP    NOT NULL
  COMMENT '注册日期',
  `USER_REAL_NAME`   VARCHAR(200) NOT NULL
  COMMENT '姓名',
  `USER_GENDER`      VARCHAR(10)  NOT NULL
  COMMENT '性别',
  `USER_AGE`         INTEGER      NOT NULL
  COMMENT '年龄',
  `USER_NATION`      VARCHAR(10)  NOT NULL
  COMMENT '民族',
  `USER_MAIL`        VARCHAR(200) NOT NULL
  COMMENT '邮箱',
  `USER_PHONE`       VARCHAR(200) NOT NULL
  COMMENT '手机',
  `USER_PHOTO`       VARCHAR(200) COMMENT '照片',
  `USER_LOCATION`    INTEGER COMMENT '所在地',
  `USER_NICKNAME`    VARCHAR(200) COMMENT '昵称',
  `ROLE_ID`          INTEGER      NOT NULL
  COMMENT '角色ID',
  `PERMI_ID`         INTEGER      NOT NULL
  COMMENT '权限ID',
  `IS_DELETE`        INTEGER      NOT NULL
  COMMENT '是否删除',
  `IS_DELETE_TIME`   TIMESTAMP    NULL DEFAULT NULL
  COMMENT '删除时间',
  PRIMARY KEY (`USER_ID`)
)
  COMMENT = '用户注册信息表';
create table IF NOT EXISTS `SYS_HR_CONFIGURATION` (
  `HR_ID`                    INT UNSIGNED AUTO_INCREMENT
  COMMENT '招聘者ID',
  `CONFIG_RECEIVE_APPLICANT` INTEGER NOT NULL
  COMMENT '是否接受推荐应聘者',
  PRIMARY KEY (`HR_ID`)
)
  COMMENT = '招聘者个人设置表';
create table IF NOT EXISTS `SYS_STU_CONFIGURATION` (
  `STU_ID`                INT AUTO_INCREMENT
  COMMENT '应聘者ID',
  `CONFIG_CV_VISIBLE`     INTEGER NOT NULL
  COMMENT '简历是否可见',
  `CONFIG_RECEIVE_MAIL`   INTEGER NOT NULL
  COMMENT '是否接受应聘邮件邀请',
  `CONFIG_RECEIVE_JOB`    INTEGER NOT NULL
  COMMENT '是否接受推荐职位',
  `CONFIG_RECEIVE_FRIEND` INTEGER NOT NULL
  COMMENT '是否接受好友推荐',
  PRIMARY KEY (`STU_ID`)
)
  COMMENT = '应聘者个人设置表';
ALTER TABLE STU_INFO
  ADD CONSTRAINT `STU_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `SYS_USER` (`USER_ID`);
ALTER TABLE STU_EDU_INFO
  ADD CONSTRAINT `STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_SUB_INFO
  ADD CONSTRAINT `SUB_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_PROJECT
  ADD CONSTRAINT `PROJ_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_WORK
  ADD CONSTRAINT `WORK_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_ACTIVITY
  ADD CONSTRAINT `ACT_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_ADVAN_LABEL
  ADD CONSTRAINT `LABEL_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_PREFER_PROF
  ADD CONSTRAINT `PRE_PROF_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_PREFER_INDUSTRY
  ADD CONSTRAINT `PRE_IND_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_PREFER_CITY
  ADD CONSTRAINT `PRE_CITY_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_PREFER_SALARY
  ADD CONSTRAINT `PRE_SALA_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_INTRODUCTION_VIDEO
  ADD CONSTRAINT `INTRO_VIDEO_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_RESUME_TEMPLATE
  ADD CONSTRAINT `TEMPLATE_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_NOTIFICATION
  ADD CONSTRAINT `NOTIFY_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE HR_INFO
  ADD CONSTRAINT `HR_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `SYS_USER` (`USER_ID`);
ALTER TABLE COMPANY_INFO
  ADD CONSTRAINT `COMP_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `SYS_USER` (`USER_ID`);
ALTER TABLE COMPANY_INDUSTRY
  ADD CONSTRAINT `COMP_IND_NUM` FOREIGN KEY (`IND_NUM`) REFERENCES `SYS_IND_CLASS` (`IND_NUM`);
ALTER TABLE COMPANY_INDUSTRY
  ADD CONSTRAINT `INDUS_COMP_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY_INFO` (`COMPANY_ID`);
ALTER TABLE COMPANY_VERIFICAITON
  ADD CONSTRAINT `VER_USER_ID` FOREIGN KEY (`OPER_USER_ID`) REFERENCES `SYS_USER` (`USER_ID`);
ALTER TABLE COMPANY_VERIFICAITON
  ADD CONSTRAINT `VER_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY_INFO` (`COMPANY_ID`);
ALTER TABLE JOB_INFO
  ADD CONSTRAINT `JOB_HR_ID` FOREIGN KEY (`HR_ID`) REFERENCES `HR_INFO` (`HR_ID`);
ALTER TABLE JOB_INFO
  ADD CONSTRAINT `JOB_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY_INFO` (`COMPANY_ID`);
ALTER TABLE JOB_INDUSTRY
  ADD CONSTRAINT `IND_JOB_ID` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB_INFO` (`JOB_ID`);
ALTER TABLE HR_VIDEO_INVITATION
  ADD CONSTRAINT `INV_STU_ID` FOREIGN KEY (`INVITE_STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE HR_VIDEO_INVITATION
  ADD CONSTRAINT `INV_HR_ID` FOREIGN KEY (`INVITE_HR_ID`) REFERENCES `HR_INFO` (`HR_ID`);
ALTER TABLE STU_JOB_COLLECT
  ADD CONSTRAINT `JOBC_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_JOB_COLLECT
  ADD CONSTRAINT `JOBC_JOB_ID` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB_INFO` (`JOB_ID`);
ALTER TABLE STU_COMP_COLLECT
  ADD CONSTRAINT `COMC_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_COMP_COLLECT
  ADD CONSTRAINT `COMC_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY_INFO` (`COMPANY_ID`);
ALTER TABLE STU_JOB_APPLY
  ADD CONSTRAINT `APPLY_STU_ID` FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO` (`STU_ID`);
ALTER TABLE STU_JOB_APPLY
  ADD CONSTRAINT `APPLY_JOB_ID` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB_INFO` (`JOB_ID`);
ALTER TABLE SYS_USER
  ADD CONSTRAINT `ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `SYS_USER_ROLE` (`ROLE_ID`);
ALTER TABLE SYS_USER
  ADD CONSTRAINT `PERMI_ID` FOREIGN KEY (`PERMI_ID`) REFERENCES `SYS_ROLE_PERMISSION` (`PERMI_ID`);
