CREATE TABLE IF NOT EXISTS SYS_COUNTRY (
  `COUNTRY_ID`   INT UNSIGNED PRIMARY KEY NOT NULL,
  `COUNTRY_NAME` VARCHAR(128)             NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_INDUSTRY (
  `INDUSTRY_ID`   INT UNSIGNED PRIMARY KEY NOT NULL,
  `INDUSTRY_NAME` VARCHAR(128)             NOT NULL
);

# 工作类型（全职，兼职...）
create TABLE IF NOT EXISTS SYS_JOB_TYPE (
  `JOB_TYPE_ID`   INT UNSIGNED PRIMARY KEY NOT NULL,
  `JOB_TYPE_NAME` VARCHAR(128)             NOT NULL
);

# 职位状态(开放，不开放)
CREATE TABLE IF NOT EXISTS SYS_JOB_STATUS (
  `JOB_STATUS_ID`   INT UNSIGNED PRIMARY KEY NOT NULL,
  `JOB_STATUS_NAME` varchar(200)             NOT NULL
);

##用户角色表
create table IF NOT EXISTS `SYS_USER_ROLE` (
  `ROLE_ID`          INT UNSIGNED AUTO_INCREMENT
  COMMENT '角色ID',
  `ROLE_TYPE`        INTEGER      NOT NULL
  COMMENT '角色类型',
  `ROLE_DESCRPTIPON` VARCHAR(100) NOT NULL
  COMMENT '角色描述',
  PRIMARY KEY (`ROLE_ID`)
)
  COMMENT = '用户角色表';

##用户注册信息表
create table IF NOT EXISTS `SYS_USER` (
  `USER_ID`          INT UNSIGNED AUTO_INCREMENT
  COMMENT '用户ID',
  `USER_NAME`        VARCHAR(200) NOT NULL
  COMMENT '登录名',
  `USER_PASS`        VARCHAR(200) NOT NULL
  COMMENT '密码',
  `USER_REGIST_DATE` TIMESTAMP    NOT NULL
  COMMENT '注册日期',
  `USER_REAL_NAME`   VARCHAR(200) NOT NULL
  COMMENT '姓名',
  `USER_GENDER`      VARCHAR(10)  NOT NULL
  COMMENT '性别',
  `USER_AGE`         INT UNSIGNED NOT NULL
  COMMENT '年龄',
  `USER_NATION`      VARCHAR(10)  NOT NULL
  COMMENT '民族',
  `USER_MAIL`        VARCHAR(200) NOT NULL
  COMMENT '邮箱',
  `USER_PHONE`       VARCHAR(200) NOT NULL
  COMMENT '手机',
  `USER_PHOTO`       VARCHAR(200) COMMENT '照片',
  `USER_LOCATION`    INT UNSIGNED COMMENT '所在地',
  PRIMARY KEY (`USER_ID`)
)
  COMMENT = '用户注册信息表';

# Company info
CREATE TABLE IF NOT EXISTS COMPANY (
  `COMPANY_ID`         INT UNSIGNED AUTO_INCREMENT
  COMMENT '企业ID',
  `COMPANY_NAME`       VARCHAR(128) NOT NULL
  COMMENT '企业名称',
  `COMPANY_CODE`       VARCHAR(128) NOT NULL
  COMMENT '企业三证号码',
  `COMPANY_COUNTRY`    int unsigned NOT NULL
  COMMENT '企业国别',
  `COMPANY_INTRODUC`   VARCHAR(200) COMMENT '企业简介',
  `COMPANY_SCALE_NUM`  INT UNSIGNED NOT NULL
  COMMENT '企业规模',
  `COMPANY_NATURE`     VARCHAR(200) NOT NULL
  COMMENT '企业性质',
  `COMPANY_LOCATION`   VARCHAR(200) NOT NULL
  COMMENT '企业所在地',
  `COMPANY_MAIL`       VARCHAR(128) COMMENT '企业邮箱',
  `COMPANY_WEBSITE`    VARCHAR(200) COMMENT '企业官网',
  `COMPANY_START_DATE` DATETIME COMMENT '成立日期',
  `COMPANY_LOGO`       VARCHAR(200) COMMENT '企业LOGO',
  PRIMARY KEY (`COMPANY_ID`)
);

CREATE TABLE IF NOT EXISTS COMPANY_INDUSTRY (
  `COMPANY_ID`  INT UNSIGNED NOT NULL,
  `INDUSTRY_ID` INT UNSIGNED NOT NULL
);

##企业认证表
create table IF NOT EXISTS `COMPANY_VERIFICATION` (
  `VERIFY_ID`       INT UNSIGNED          AUTO_INCREMENT
  COMMENT '认证ID',
  `COMPANY_ID`      INT UNSIGNED NOT NULL
  COMMENT '公司ID',
  `VERIFY_TIME`     TIMESTAMP    NOT NULL DEFAULT NOW()
  COMMENT '认证时间',
  `VERIFY_END_TIME` TIMESTAMP    NOT NULL DEFAULT NOW()
  COMMENT '到期时间',
  `OPER_USER_ID`    INT UNSIGNED NOT NULL
  COMMENT '操作人',
  PRIMARY KEY (`VERIFY_ID`)

)
  COMMENT = '企业认证表';

##企业职位映射表
create table IF NOT EXISTS `COMPANY_JOB_MAP` (
  `JOB_ID`     INT UNSIGNED AUTO_INCREMENT
  COMMENT '职位ID',
  `COMPANY_ID` INT UNSIGNED NOT NULL
  COMMENT '企业ID',
  PRIMARY KEY (`JOB_ID`)
)
  COMMENT = '企业职位映射表';

##职位基本信息表
create table IF NOT EXISTS `JOB` (
  `JOB_ID`          INT UNSIGNED AUTO_INCREMENT
  COMMENT '职位ID',
  `JOB_NAME`        VARCHAR(200) NOT NULL
  COMMENT '职位名称',
  `JOB_PROF_NUM`    INT UNSIGNED NOT NULL
  COMMENT '职位类别编号',
  `JOB_START_TIME`  DATE         NOT NULL
  COMMENT '职位起始时间',
  `JOB_END_TIME`    DATE         NOT NULL
  COMMENT '职位截止时间',
  `JOB_TYPE`        INT UNSIGNED NOT NULL
  COMMENT '是否全职',
  `JOB_DESCRIPTION` VARCHAR(200) NOT NULL
  COMMENT '职位描述',
  `JOB_DUTY`        VARCHAR(200) COMMENT '职责描述',
  `JOB_REQ`         VARCHAR(200) COMMENT '学历要求',
  `JOB_LOCATION`    VARCHAR(200) NOT NULL
  COMMENT '工作地点',
  `JOB_HIGHLIGHT`   VARCHAR(200) COMMENT '职位亮点',
  `JOB_SALARY`      VARCHAR(200) COMMENT '职位薪资（非必填）',
  `CV_RECEI_MAIL`   VARCHAR(200) NOT NULL
  COMMENT '简历接收邮箱',
  `CV_NAME_RULE`    VARCHAR(200) COMMENT '简历命名规则,Regex',
  `JOB_ACTIVE`      INT UNSIGNED NOT NULL
  COMMENT '职位状态',
  PRIMARY KEY (`JOB_ID`)
)
  COMMENT = '职位基本信息表';

ALTER TABLE COMPANY
  ADD CONSTRAINT COMPANY_SYS_COUNTRY_COUNTRY_ID_fk
FOREIGN KEY (COMPANY_COUNTRY) REFERENCES SYS_COUNTRY (COUNTRY_ID);

ALTER TABLE COMPANY_VERIFICATION
  ADD CONSTRAINT COMPANY_VERIFICATION_COMPANY_COMPANY_ID_fk
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  ADD CONSTRAINT COMPANY_VERIFICATION_SYS_USER_USER_ID_fk
FOREIGN KEY (OPER_USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE COMPANY_INDUSTRY
  ADD CONSTRAINT COMPANY_INDUSTRY_COMPANY_COMPANY_ID_fk
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  ADD CONSTRAINT COMPANY_INDUSTRY_INDUSTRY_INDUSTRY_ID_fk
FOREIGN KEY (INDUSTRY_ID) REFERENCES SYS_INDUSTRY (INDUSTRY_ID);

ALTER TABLE COMPANY_JOB_MAP
  ADD CONSTRAINT COMPANY_JOB_MAP_COMPANY_COMPANY_ID_fk
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);

ALTER TABLE JOB
  ADD CONSTRAINT JOB_SYS_JOB_TYPE_JOB_TYPE_ID_fk
FOREIGN KEY (JOB_TYPE) REFERENCES SYS_JOB_TYPE (JOB_TYPE_ID);
ALTER TABLE JOB
  ADD CONSTRAINT JOB_SYS_JOB_STATUS_JOB_STATUS_fk
FOREIGN KEY (JOB_ACTIVE) REFERENCES SYS_JOB_STATUS (JOB_STATUS_ID);