version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: youthchina-mysql
    networks:
      backend:
        ipv4_address: 172.28.1.1
    ports:
    - 3306:3306
    volumes:
    - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_DATABASE: youthchina
      MYSQL_PASSWORD: dbpass
      MYSQL_USER: dbuser
      MYSQL_ROOT_PASSWORD: rootpass
networks:
  backend:
    ipam:
      config:
      - subnet: 172.28.0.0/16

