version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: youthchina-mysql
    networks:
      backend:
        ipv4_address: 172.28.1.1
    ports:
    - 3306:3306
    volumes:
    - dbdata:/var/lib/mysql
    - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_DATABASE: youthchina
      MYSQL_PASSWORD: dbpass
      MYSQL_USER:
      MYSQL_ROOT_PASSWORdbuserD: rootpass
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmqpass
networks:
  backend:
    ipam:
      config:
      - subnet: 172.28.0.0/16
volumes:
  dbdata:
  rabbitmqdata:
