# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    parallelism: 1

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mv ~/repo/.circleci/spring.application.properties ~/repo/src/main/resources/application.properties
      - run: mv ~/repo/.circleci/spring.config.properties ~/repo/src/main/resources/config.properties
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: docker-compose down -v
      - run: docker-compose up -d

      - run: mvn test -Dtest=StudentMapperTest # why?
      - run: mvn integration-test

      # This line is to be able to access failing screenshots in the
      # artifacts section in CircleCI
      - store_artifacts:
          path: ~/repo/features/fail-screenshots

#      - run:
#          name: Deploy Over SSH
#          command: |
#            ssh $SSH_USER@$SSH_HOST "~/backend/deploy.sh"



